
package calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Adder", targetNamespace = "http://calculator/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Adder {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://calculator/", className = "calculator.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://calculator/", className = "calculator.SubstractResponse")
    @Action(input = "http://calculator/Adder/substractRequest", output = "http://calculator/Adder/substractResponse")
    public double substract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://calculator/", className = "calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calculator/", className = "calculator.AddResponse")
    @Action(input = "http://calculator/Adder/addRequest", output = "http://calculator/Adder/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
